<a href="https://colab.research.google.com/github/SupunTSW/Mastering-PyTorch/blob/main/01_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

##Initializing a Tensor

In [ ]:
#initializing a tensor (Direct from data)
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [ ]:
#initializing a tensor (From a numpy array)
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [ ]:
#initializing a tensor(From another Tensor)
x_ones = torch.ones_like(x_np)
print(f"Ones Tensor: \n {x_ones} \n") # retains the properties of x_data

x_rand = torch.rand_like(x_data, dtype = torch.float) # overide the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2621, 0.6298],
        [0.1358, 0.3582]]) 



In [ ]:
#initializing a tensor(With random or constant value)
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")


Random Tensor: 
 tensor([[0.4542, 0.9257, 0.6449],
        [0.6397, 0.5961, 0.2242]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


##Attributes of a Tensor

In [ ]:
#Atrributes of a Tensor (Shape, datatype, and device on which they are stored)
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


##Operations on Tensor

In [ ]:
#Move the tensor to the current accelerator if available
if torch.accelerator.is_available():
  tensor = tensor.to(torch.accelerator.current_accelerator())

In [ ]:
#standard numpy-like indexing and slicing
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
#Joining tensors using torch.cat
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


#Arithmatic Operations

In [ ]:
#this computes the matrix multipliation between two tensors. y1, y2, y3 will have the same value

y1 = tensor @ tensor.T #"tensor.T" returns the transpose of a tensor
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)

torch.matmul(tensor, tensor.T, out=y3)

#this computes the element-wise product. z1, z2, z3 will have the same value

z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)

torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [ ]:
#Single element tensor
agg = tensor.sum()
agg_item = agg.item() #covert it to a python numerical value
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [ ]:
#In-place operations
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


##Bridge with Numpy{#bridge-to-np-label} - Tensor to Numpy array

In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [ ]:
#A change in the tensor reflects in the numpy array
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


##Bridge with Numpy{#bridge-to-np-label} - Numpy array to Tensor

In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

In [ ]:
#changes in the Numpy array reflects in the tensor
np.add(n, 1, out = n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
